import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";

const ttWellingtonsFont = localFont({
  variable: "--font-tt-wellingtons",
  src: [
    {
      path: "./fonts/TTWellingtonsTrialThin.ttf",
      weight: "100",
    },
    {
      path: "./fonts/TTWellingtonsTrialExtraLight.ttf",
      weight: "200",
    },
    {
      path: "./fonts/TTWellingtonsTrialLight.ttf",
      weight: "300",
    },
    {
      path: "./fonts/TTWellingtonsTrialRegular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/TTWellingtonsTrialMedium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/TTWellingtonsTrialSemiBold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/TTWellingtonsTrialBold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/TTWellingtonsTrialExtraBold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/TTWellingtonsTrialBlack.ttf",
      weight: "900",
    },
  ],
});

export const metadata: Metadata = {
  title: {
    default: "Aara Tech",
    template: "%s | Aara Tech",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ttWellingtonsFont.variable} `}>
        <Provider>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
